### ISSUE TITLE
Display posterior probabilities as a measure of confidence

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/R2DT#54]
We can use Infernal posterior probabilities to colour the diagrams to indicate how well the sequence is aligned to the template.

**Comment by AntonPetrov** [comment]
Hi David! @davidhoksza 

Now that Traveler supports the new JSON output format, I think it is a good time to revisit this issue. The basic idea is to be able to colour SVGs using arbitrary values, in these cases Infernal posterior probabilities.

I was thinking that Traveler could take an additional optional input file with per-residue data like this:

```
G   1.0
U   0.9
U   0.8
A   0.7
G   0.7
C   0.9
G   1.0
```

and propagate these values to the JSON file as attributes and to the SVG file as CSS classes. 

In this particular case the CSS classes could map to every 0.1 step from 0.1 to 1.0 to a colour from a [colour-blind safe palette](https://thenode.biologists.com/data-visualization-with-flying-colors/research/). This could be the default option.

In general the same approach could apply to other types of data, like structure probing reactivities or distance in 3D space, so there should be a way to provide user-specified colour mappings (for example 0.1-0.7 green, 0.7-0.75 blue, 0.75-1.0 yellow).

I created a toy example for [URS000008638F](https://rnacentral.org/rna/URS000008638F) with a data file and a JSON file to make this a bit more specific:

- [URS000008638F-posterior-probs.txt](https://github.com/RNAcentral/R2DT/files/8918167/URS000008638F-posterior-probs.txt)
- [URS000008638F_224308-RF00162.colored.json.txt](https://github.com/RNAcentral/R2DT/files/8918171/URS000008638F_224308-RF00162.colored.json.txt)

What do you think of this approach? Does it belong in the core Traveler or should it be a separate utility script that adds data to JSON and/or SVG files?

CC @aspetr01 @blakesweeney @nawrockie

**Comment by davidhoksza** [comment]
I think it should not be part of the core of Traveler because when Traveler is used outside of R2DT it does not make sense and it is, strictly speaking, not part of the layouting process. On the other hand, we should have this information in JSON (not only SVG) so that this information could be acted upon by other tools. 

So what I suggest is that I would create another script next to the one which converts JSON to SVG and this script would enable adding an arbitrary information to the JSON. Then, in the pipeline, we would create layout in JSON -> enrich the JSON with confidence scores (the new script) -> convert to SVG (the existing script - modified to take into account).

**Comment by AntonPetrov** [comment]
@davidhoksza Yep, I agree that this should be a separate utility and that it should go through JSON. If you could integrate it with the other utilities you've developed, that would be fantastic!

One thing to consider is whether this should be all backend-based as we've talked about up till now, or whether we also make this functionality available on the front-end.

I am thinking of the following use case: a user submits a sequence, generates a layout and then uploads/pastes a file with scores to visualise them, perhaps tweaks the scores and re-uploads them to get a new diagram. Or the user could save the JSON file, come back to the editor at another time and load a different set of scores (while being sure that the layout itself is unmodified). If everything is done on the backend, the user would have to rerun R2DT and regenerate the layout every time (and it could potentially change).

An alternative solution would be to produce JSON in the R2DT pipeline, serve it to the user, and generate SVG on the client side. If desired, the user could upload scores and visualise additional layers of information without a roundtrip to the EBI servers, all in the browser. 

We could approach this in two steps: follow the backend approach at first since it's the easiest to deploy, then if the users like it, make it possible to do more on the client side. Does this sound like a good plan?

**Comment by davidhoksza** [comment]
@AntonPetrov In order for the solution to be more general I suggest

- Adding column names, so that multiple annotations can be added and easily identified in the resulting JSON
- Adding residue index, so that not every residue has to be annotated
- Possibly removing the residue name column as this should be derivable from the residue index (maybe the only reason to keep it would be for validation purposes)

What do you think?

**Comment by AntonPetrov** [comment]
Good ideas, thanks @davidhoksza! I would keep the nucleotide name to simplify validation as you say, otherwise it could be hard to track down any errors.

I will start working on generating the files for posterior probabilities then. I will let you know when I have some progress but it should not stop you from prototyping the code using a simple example above if you like.

**Comment by davidhoksza** [comment]
@AntonPetrov There is a new ``enrich_json.py`` script in the utils directory of the [json branch of Traveler](https://github.com/cusbg/traveler/tree/json), which should do what we discussed above. The usage is described in the [utils README](https://github.com/cusbg/traveler/tree/json/utils). Please let me know if this does what you expected. No problem to change the behavior, column naming and so on...

**Comment by AntonPetrov** [comment]
@davidhoksza This is cool, thanks a lot David! I will try the script and report any issues. 

How do you envision translating these annotations to CSS classes in the SVG? Do you think it's something for Traveler or for the JS component?

**Comment by davidhoksza** [comment]
@AntonPetrov I was first thinking about integrating this into the script as well, but then I realized it's probably not possible in general. The problem is that the domain of an annotation can be real-valued and therefore there could be "infinitely" many possible values for the color. Thus, you can't specify the color using a class. I could generate the colors directly (provided the user specified the color range using min-max values and color for those values) , however, then the information would have to be be stored as a color code in the ``color`` attribute and it would be pretty complicated for the application to change the colors. 

So I thought it would be wiser to leave it to the application. What I could do is to propagate the values in the enriched JSON to the SVG as attribute values, so that the application could still work only with the SVG (and would not need to parse the JSON to look for the annotation values). What do you think?

One disadvantage of this is that color coding information is not stored neither in the JSON nor in the SVG. But since this information is not present in the input TSV, I think this is actually correct.

But there might be a more elegant solution which I am missing. So I am open to any suggestions, of course!

**Comment by nawrockie** [comment]
Actually there are 11 possible values: `0`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `*`. 

`*` is used for the highest posterior probability (>=0.95) meaning the highest level of confidence that the corresponding nucleotide is aligned correctly, and `0` is the lowest. `*` will be the most common of the 11 possible values.

**Comment by davidhoksza** [comment]
I added the possibility to add params file with the coloring specification to the json2svg utility. The documentation is updated, including examples (`URS000080E2F0_93929-RF01734.enriched.json` and `URS00002A2E83_10090-HS_SSU_3D.enriched.json`) provided by @AntonPetrov in Slack. Apart from the coloring, the titles of the residues now show not only the position but also the attribute value.

The code is currently only available in the [json branch](https://github.com/cusbg/traveler/tree/json) of Traveler. This is just the first draft. I expect I will need to modify based on your feedback @AntonPetrov .

<img src="https://user-images.githubusercontent.com/3602803/204388175-731e3a78-d9e1-4712-9fa9-8d6e81e0ae31.svg" width="100%">

**Comment by AntonPetrov** [comment]
@davidhoksza This is very nice, thank you! It is working in my hands, and I can see the new colors and labels 🎉

One thing that I did not realize is that it is not possible to set `background-color` for SVG text without [workarounds](https://stackoverflow.com/questions/15500894/background-color-of-text-in-svg) like drawing a `rect` behind the letter. This is a problem because currently the colors indicate not only the insertion/reposition status of the residue, but also the posterior probability.

An ideal solution would involve changing background color in a performant way with cross-browser support. This would also allow more natural display of SHAPE reactivity data which is usually shown as background color (here is an [example](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7736786/figure/F1/)). I will look into this but it seems like it could be difficult to achieve for large diagrams like LSU.

If that's not possible, we will need to use JavaScript to switch between coloring schemes for the nucleotides. For example, the posterior probability classes could be initially written out as `inactive-color-posterior_probability-7_0` (without defining this class) so that the color is not visible initially, and when the users toggles a UI element, the `inactive-` label is added to the currently active classes and deleted from the posterior probability classes. I think something like this is already done in the R2DT widget to show the diagram with or without colors.
